Add fetch channel webhooks method
jnsougata/discohook pull request #28
Opened 2023-09-21 09:02 UTC by imptype

2023-10-12 03:02 UTC, jnsougata requested changes
It will result in a circular import. Rather return the raw payload for now

2023-11-16 02:44 UTC, jnsougata requested changes
remove redundant client imports

2025-01-05 16:39 UTC, jnsougata approved these changes

2025-04-17 19:34 UTC, imptype commented
Closing because outdated, see #65

2025-04-17 19:34 UTC, closed without merging