Add string option to autocomplete
jnsougata/discohook pull request #36
Opened 2023-11-10 20:35 UTC by imptype

Autocomplete supports `STRING` option:
![image](https://github.com/jnsougata/discohook/assets/106537315/9d433355-6d94-4d4e-989f-e8558d365451)

Right now a command that has an autocomplete string option would just be ignored (the option payload is `autocomplete=False`)
```py
@discohook.command.slash('test', description = 'test stuff', guild_id = SUPPORT_SERVER_ID, options = [
  discohook.Option.string('choice', 'Type and select a choice.', autocomplete = True)
])
async def test_command(interaction):
  await interaction.response.send('content')

@test_command.autocomplete(name = 'choice')
async def choice_autocomplete(interaction, value):
  print('here!')
  await interaction.response.autocomplete([])
```
after this commit, syncing makes the option payload `autocomplete=True` because it passes that if check

2023-11-11 02:18 UTC, jnsougata requested changes
I think you didn't go through the code properly. However adding `self.data["autocomplete"] = self.autocomplete` this where the option is a string is being checked will fix the issue you are talking about.

2023-11-11 13:11 UTC, imptype commented
> However adding `self.data["autocomplete"] = self.autocomplete` this where the option is a string is being checked will fix the issue you are talking about.

It doesn't reach that line because the option type `string` doesn't pass this if check, even though it's allowed in the docs. This is what the commit fixes.
![image](https://github.com/jnsougata/discohook/assets/106537315/4f5946d7-4b99-4d48-b34b-c7dcd8521598)

2023-11-11 13:31 UTC, jnsougata commented
check line for 197. The number types allows different set of attributes that's why the check doesn't include string type.

2023-11-11 17:13 UTC, imptype commented
Makes sense.

2023-11-12 04:47 UTC, jnsougata approved these changes
🥳

2023-11-12 04:47 UTC, merged