Fix HTTPException message
jnsougata/discohook pull request #59
Opened 2024-07-24 20:20 UTC by imptype

1. Fix HTTPException erroring when getting content types other than `application/json`.
![image](https://github.com/user-attachments/assets/b69ec582-f855-468e-b496-01ce47e0a433)

2. Be more explicit with the response data. Sometimes it doesn't have the "code" key in it, but it is a valid json.
![image](https://github.com/user-attachments/assets/3f16c76d-9e51-4302-8203-cfee4bdeb3c0)

2024-07-25 04:55 UTC, jnsougata requested changes
As we are passing the `resp` object ref inside the Exception class so it will be good to hide the content_type check within the class rather than putting it in the global `_handler` for clarity.

2024-07-25 23:09 UTC, imptype commented
> As we are passing the `resp` object ref inside the Exception class so it will be good to hide the content_type check within the class for clarity, rather than putting it in the global `_handler`.

We can't move the content_type check inside the class because you can't use `await` in `__init__`. There are other ways to async init but it's messier than what we have now.

2024-07-26 16:28 UTC, jnsougata commented
> > As we are passing the `resp` object ref inside the Exception class so it will be good to hide the content_type check within the class for clarity, rather than putting it in the global `_handler`.
> 
> We can't move the content_type check inside the class because you can't use `await` in `__init__`. There are other ways to async init but it's messier than what we have now.

In that case, we can just add those awaited values to the error obj before raising exception or  we can add `response` attr to the Error class.

2025-02-05 20:14 UTC, imptype commented
If we REALLY want to avoid checking the response's content-type outside and put it inside the HTTPException class instead for the sake of making the code in `https.py` look less and cleaner, the only decent way to do it is using an async class method

So instead of
```py
        if resp.status >= 400:
            raise HTTPException(resp, await resp.json())
```
it's now
```py 
        if resp.status >= 400:
            raise await HTTPException.create(resp)
```
and the check and async reads are in the async `create` method.

2025-04-17 18:25 UTC, imptype commented
Closing because httpexceptions were fixed in refactor

2025-04-17 18:25 UTC, closed without merging